name: pedometer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  daily_pedometer2: ^1.1.3
  flutter:
    sdk: flutter
  pedometer: ^4.0.1
  provider: ^6.1.2
  sensors_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
